package: product
version: '3.0.0-beta1'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/product/

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.10
    packages:
        yform: ">=3.4"
        yform_field: ">1"


page:
    title: translate:product
    main: true
    block: system
    prio: 19
    icon: rex-icon fa-cube
    perm: product[]
    subpages: 
        category:
            title: translate:product_category
            icon: rex-icon fa-cube
            perm: product[category]
        product:
            title: translate:product
            icon: rex-icon fa-cube
            perm: product[product]
        variant:
            title: translate:product_variant
            icon: rex-icon fa-cube
            perm: product[variant]
        settings:
            title: translate:product_settings
            icon: rex-icon fa-gear
            itemclass: pull-right
            perm: admin
        docs:
            title: translate:product_docs
            icon: rex-icon fa-info-circle
            itemclass: pull-right
            perm: product[docs]

default_config:
